name: build

on:
  push:
    branches: [master]

jobs:
  x86_64-linux-gnu-gcc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Install prerequisites
        run: |
          sudo apt update -y
          sudo apt install -y '^libxcb.*-dev' libglu1-mesa-dev libx11-xcb-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libxrender-dev ninja-build
      - run: cmake --preset "Release x86_64-linux-gnu-gcc"
        env:
          CC: gcc-10
          CXX: g++-10
      - run: cmake --build build --parallel --target QtESPFlasher
      - name: Find archive file
        run: |
          echo "ARTIFACT_NAME=$(find build -type f -name "QtESPFlasher-*.zip" -printf "%f\n")" >> $GITHUB_ENV
          echo "ARTIFACT_PATH=$(find build -type f -name "QtESPFlasher-*.zip")" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}

  x86_64-w64-mingw32-gcc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Install prerequisites
        run: |
          sudo apt update -y
          sudo apt install -y libz-mingw-w64 libz-mingw-w64-dev mingw-w64 ninja-build
          sudo pip install aqtinstall --break-system-packages
      - run: cmake --preset "Release x86_64-w64-mingw32-gcc"
      - run: cmake --build build --parallel --target QtESPFlasher
      - name: Find archive file
        run: |
          echo "ARTIFACT_NAME=$(find build -type f -name "QtESPFlasher-*.zip" -printf "%f\n")" >> $GITHUB_ENV
          echo "ARTIFACT_PATH=$(find build -type f -name "QtESPFlasher-*.zip")" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
